In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [58]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9740740740740741

In [59]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [60]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9592592592592593

In [61]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [62]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [63]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
        digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(
        solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))

    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))

    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [64]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [65]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [66]:
scores_rf

[0.9365609348914858, 0.9432387312186978, 0.9148580968280468]

In [67]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), digits.data, digits.target).mean()

0.9221138966264315

In [68]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target).mean()

0.448545341999381

In [69]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target).mean()

0.9337991333952337